apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlynar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlynar
  template:
    metadata:
      labels:
        app: mlynar
    spec:
      serviceAccountName: mlynar-sa
      containers:
      - name: mlynar
        image: ffluffyhedgehog/mlynar:0.1.41
        imagePullPolicy: Always
        env:
        - name: RUN_MOUNT_DIR
          value: "/runs"
        - name: SERVICE_NAME
          value: mlynar-service
        - name: SERVICE_PORT
          value: "3000"
        envFrom:
          # MINIO_SERVICE_NAME, MINIO_SERVICE_PORT, MINIO_ACCESS_KEY, MINIO_SECRET_KEY, MINIO_BUCKET_NAME
          # go in these secrets
          - secretRef:
              name: minio-secrets
          # adminPassword, adminUsername, cookieAuthSecret, erlangCookie, COUCHDB_SERVICE_NAME, COUCHDB_SERVICE_PORT
          # go in these secrets
          - secretRef:
              name: mlynar-couchdb-couchdb
        volumeMounts:
        - name: run-volume
          mountPath: /runs
      volumes:
      - name: run-volume
        persistentVolumeClaim:
          claimName: mlynar-pvc